name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build_and_deploy_job:
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed') }}
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_SEA_034B06D1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # For GitHub integrations (e.g., PR comments)
          action: "upload"
          ###### Repository/Build Configurations ######
          # Ensure these paths match your app's structure
          app_location: "/project1" # Adjust to the root folder of your app
          api_location: ""          # Optional: Adjust if your app includes an API
          output_location: "/"      # Ensure this matches the build output directory
          ###### End of Configurations ######

  close_pull_request_job:
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_SEA_034B06D1E }}
          action: "close"
